server:
  port: 8081
mybatis:
  type-aliases-package: com.exaple.demo.entity
  mapper-locations: classpath:dao/*Mapper.xml
  #禁用掉模板缓冲，在开发环境中可以实时的观察到html页面的更改
  spring:
    thymeleaf:
      cache: false
spring:
  datasource:
#    url: jdbc:mysql://localhost:8081/jeecg-boot?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: yjcsxdl.
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: yjcsxdl.
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计的filters，去掉后监控界面sql无法统计，wall用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
